version: '3.3'
volumes:
  data:
services:
  app:
    container_name: claro-app
    build: .
    links:
     - mysql:mysql
    depends_on:
      - mysql
    ports:
     - "3000:3000"

  mysql:
    container_name: database-mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_DATABASE=clarodb

